title: "Theodore NOUBISSI KALA"
logo: img/theodore.jpg
description: "Portfolio Data Scientist – Machine Learning, Automatisierung, Data Science"
show_downloads: true
theme: jekyll-theme-minimal
lang: de
