title: "Theodore NOUBISSI KALA"
logo: img/Bildschirmfoto 2025-09-06 um 14.25.35.png
description: "Portfolio Data Scientist – Machine Learning, Automatisierung, Data Science"
show_downloads: true
theme: jekyll-theme-minimal
lang: de
